### ISSUE TITLE
Another bugs?

### ISSUE THREAD

**Issue by ShardedFilms** [AvantTeam/ProjectUnityPublic#14]
[crash-report-02_08_2022_22_06_14.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8025006/crash-report-02_08_2022_22_06_14.txt)

**Comment by Xeloboyo** [comment]
thats a rare one, can you give more context?

**Comment by Xeloboyo** [comment]
No clue what happened there. Assuming its fixed.
