### ISSUE TITLE
???crash.fraction.select???

### ISSUE THREAD

**Issue by ShardedFilms** [AvantTeam/ProjectUnityPublic#17]
[crash-report-02_09_2022_12_40_38.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8029822/crash-report-02_09_2022_12_40_38.txt)

**Comment by StudioSharded** [comment]
i disabled all fractions.. and go to another map and enable them.. and its happens...

**Comment by Xeloboyo** [comment]
thanks, it should be resolved in the next update
