### ISSUE TITLE
Modular Unit Suggestions

### ISSUE THREAD

**Issue by Dryehm** [AvantTeam/ProjectUnityPublic#18]
Parts: 
A faster version of the 1 by 1 gun
Armor plating 
Swarmer like cannon
Railgun
Self-repairing block
Segment like defensive block
Reactive armor (surge plating)

Ideas:
Make tracks be a bit faster
A custom AI for the unit to shoot because it just runs into enemy defense and dies
Mirror option for the 4 quadrants

**Comment by MEEPofFaith** [comment]
Issues are not for suggestions.

**Comment by Dryehm** [comment]
xelo told me to use issues tho

**Comment by Dryehm** [comment]
:despair:

**Comment by SMOLKEYS** [comment]
meep


every other repo uses issues for suggestions

**Comment by MEEPofFaith** [comment]
![image](https://user-images.githubusercontent.com/54301439/153135195-529622ae-3552-478c-aa88-b40f0b205390.png)
