### ISSUE TITLE
NullPointer on unselecting

### ISSUE THREAD

**Issue by uujuju1** [AvantTeam/ProjectUnityPublic#22]
[crash-report-02_14_2022_14_32_17.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8062775/crash-report-02_14_2022_14_32_17.txt)
somehow crashed when unselecting nickel wall on the payload caster

**Comment by Xeloboyo** [comment]
Known bug where you can swap out what its crafting during its crafting, it tries to craft nothing and crashes.
Will be fixed in next commit.

**Comment by uujuju1** [comment]
ey
