### ISSUE TITLE
Level one

### ISSUE THREAD

**Issue by ShardedFilms** [AvantTeam/ProjectUnityPublic#23]
[crash-report-02_15_2022_22_41_21.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8072522/crash-report-02_15_2022_22_41_21.txt)

**Comment by StudioSharded** [comment]
i just use a laser turret

and crash on level one..

**Comment by ShardedFilms** [comment]
koruh

**Comment by Xeloboyo** [comment]
branch is incomplete rn, please do not test until it merges into master for the first time.

**Comment by sk7725** [comment]
> branch is incomplete rn, please do not test until it merges into master for the first time.

(Actually please do)

**Comment by sk7725** [comment]
fixed
