### ISSUE TITLE
Placing Laser t-breakthrough to Laser T-shard crash the game

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [AvantTeam/ProjectUnityPublic#24]
https://user-images.githubusercontent.com/82627347/154111850-c6ebd198-be98-4567-9fb7-ebc3c0898bab.mp4

[crash_1644944356213.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8073063/crash_1644944356213.txt)

**Comment by Goobrr** [comment]
Thanks for testing, the exp branch is very unstable right now so i suggest to avoid casually playing with it before it merges to master for the first time.

@sk7725
