### ISSUE TITLE
NEVER replace crucible block next to crucible source... IN THE EXACT SAME LOCATION>

### ISSUE THREAD

**Issue by Lussitonic** [AvantTeam/ProjectUnityPublic#26]
![image](https://user-images.githubusercontent.com/98243595/154381514-53101aa2-78ff-4767-8462-54eaf79b3e19.png)
Just don't.

**Comment by Lussitonic** [comment]
will give further documentation soon

**Comment by Lussitonic** [comment]
wait it's a problem with the way i downloaded
ok time to close

**Comment by GlennFolker** [comment]
> wait it's a problem with the way i downloaded ok time to close

???

**Comment by Lussitonic** [comment]
More context: Turns out i freaking downloaded youngcha-part 2
so it's an issue with that

**Comment by GlennFolker** [comment]
> More context: Turns out i freaking downloaded youngcha-part 2 so it's an issue with that

Then it's still a perfectly valid issue.

**Comment by Lussitonic** [comment]
...Now that i think about it, i'll have to do more testing.
I'll use the latest version of it for this.

**Comment by Lussitonic** [comment]
...Appears the issue was fixed. Gonna test it a bit more then get back
