### ISSUE TITLE
Reloading the world with empty menus can cause... issues...

### ISSUE THREAD

**Issue by MEEPofFaith** [AvantTeam/ProjectUnityPublic#27]
https://user-images.githubusercontent.com/54301439/154393797-d96b83e8-8d75-4559-97bc-d248dc0a8e76.mp4

[crash-report-02_16_2022_18_34_42.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8085093/crash-report-02_16_2022_18_34_42.txt)

**Comment by sk7725** [comment]
.....THAT BUTTON EXISTED?
That...actually breaks a lot of WorldLoadEvent-based stuff, including stuff from private pu and bm and oh fuck

**Comment by MEEPofFaith** [comment]
~~what did you think the sharded button was?~~

**Comment by Lussitonic** [comment]
by the way, appears that this issue was reported earlier on but was completely ignored.
this was opened 14 days ago, and that issue is 22 days ago.

**Comment by Xeloboyo** [comment]
This issue no longer causes a crash in my branch, but categories still remain affected

**Comment by sk7725** [comment]
> ~what did you think the sharded button was?~

I meant the Load Game button, which for some reason does not fire a WLE

**Comment by MEEPofFaith** [comment]
maybe that's why explosions of bullets in one world deal damage to another after hitting Load Game

**Comment by Xeloboyo** [comment]
Mostly fixed in latest youngcha branch
