### ISSUE TITLE
Small/Large exp node can't level up walls when loading a save

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [AvantTeam/ProjectUnityPublic#28]
https://user-images.githubusercontent.com/82627347/154419224-c4c4cdc9-4cdd-4931-925b-90df0f22c860.mp4

**Comment by Lussitonic** [comment]
how is this not closed lol

**Comment by Xeloboyo** [comment]
@sk7725 is this resolved? :0

**Comment by sk7725** [comment]
i think so
