### ISSUE TITLE
Wheels do be a game breaker

### ISSUE THREAD

**Issue by Lussitonic** [AvantTeam/ProjectUnityPublic#34]
![image](https://user-images.githubusercontent.com/98243595/158024748-adf75372-cfdb-4da7-a1bb-2d7947ca4cb2.png)

add one wheel...

![image](https://user-images.githubusercontent.com/98243595/158024776-77b991c4-f413-406d-8e51-1b01fa6d8bff.png)

**Comment by Lussitonic** [comment]
oh cool, new release, did you fix the issue?

**Comment by Xeloboyo** [comment]
should be resolved.
