### ISSUE TITLE
Game crashes when i try to control a "Modular Unit"

### ISSUE THREAD

**Issue by cringe69ok** [AvantTeam/ProjectUnityPublic#36]
I was trying out the Sandbox Assembler, when i spawned and controlled a modular unit, the game crashed. This is the error. 
![Screenshot 2022-03-14 123142](https://user-images.githubusercontent.com/92081120/158105309-93d25083-947c-4650-b08c-972abc94e6ca.png)

**Comment by cringe69ok** [comment]
I forgot, you can command it.

**Comment by Xeloboyo** [comment]
id need the full crash log, not just the error message

**Comment by cringe69ok** [comment]
ok
![Screenshot 2022-03-14 134214](https://user-images.githubusercontent.com/92081120/158111930-72c080af-8990-4d13-b9c3-75931df9d201.png)

**Comment by Xeloboyo** [comment]
try it without the custom client and the mods...
the piece of code that is throwing an error does not exist normally.

**Comment by cringe69ok** [comment]
mk

**Comment by cringe69ok** [comment]
on the normal version without mods except project unity it says that i have mods with errors, it also appears to have errors with content too

**Comment by cringe69ok** [comment]
the content errors show units from the mod

**Comment by Xeloboyo** [comment]
try a fresh install, noone else has had this issue as far as I know.

**Comment by cringe69ok** [comment]
it still won't work on a fresh install, it shows the same thing (it is probably my pc or something)

**Comment by GlennFolker** [comment]
> (it is probably my pc or something)

It never is.

**Comment by Lussitonic** [comment]
> > (it is probably my pc or something)
> 
> It never is.

tell that to my corrupted drive a few months ago

**Comment by cringe69ok** [comment]
well i guess i will stick to commanding the units now
