### ISSUE TITLE
When select 'Crucible Pump' in Payload Source

### ISSUE THREAD

**Issue by ShardedFilms** [AvantTeam/ProjectUnityPublic#37]
did -

[crash-report-03_14_2022_13_07_31.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/8242139/crash-report-03_14_2022_13_07_31.txt)

**Comment by StudioSharded** [comment]
~Youngcha2

**Comment by StudioSharded** [comment]
and i cannot join the server

**Comment by ShardedFilms** [comment]
crash on system

**Comment by Xeloboyo** [comment]
Should be fixed in next commit.

**Comment by StudioSharded** [comment]
also... any youngcha block output with payload source are... crash the game
