### ISSUE TITLE
tres sus gas multipus issusus

### ISSUE THREAD

**Issue by SMOLKEYS** [AvantTeam/ProjectUnityPublic#39]
crashus
1. Place payload arm
2. Give it rotational energy
3. Use mega to place in payload conv
4. 
```
NullPointer: 'Attempt to read from field 'mindustry.gen.Building mindustry.world.Tile.build' on a null object reference'
PayloadArm$PayloadArmBuild.updateTile: 333
Building.update: 1223
BuildPayload.update: 44
PayloadBlock$PayloadBlockBuild.updateTile: 141
PayloadVoid$PayloadVoidBuild.updateTile: 58
Building.update: 1223
EntityGroup.update: 59
Groups.update: 75
Logic.update: 413
ApplicationCore.update: 37
ClientLauncher.update: 177
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1571
GLSurfaceView$GLThread.run: 1270
```
---
renderus issus

1. Make payload arm
2. Carry torque source/meter with payload arm
3. Arm draw() ceases to function
4. there is no 4, now watch this: 
![Screenshot_20220315-181606_Mindustry](https://user-images.githubusercontent.com/75618732/158356360-849aabbe-39bc-4704-b9eb-17c0f07dc507.jpg)

---
connectus issurus

1. Place 2 drive shafts
2. Carry one with mega
3. Place it back, but make it face a different direction
4. 
![SmartSelect_20220315-181136_Mindustry](https://user-images.githubusercontent.com/75618732/158355952-67b97268-3910-4cea-8f63-7c70bb5fa9bf.jpg)
![SmartSelect_20220315-181101_Mindustry](https://user-images.githubusercontent.com/75618732/158355963-a7b5de3e-a973-4081-93e8-9d53604371db.jpg)

**Comment by Xeloboyo** [comment]
Fixed in next commit
