### ISSUE TITLE
Steam Piston and Fly Wheel Long Stick Link Sprite on Editor

### ISSUE THREAD

**Issue by Hot-Sausage07** [AvantTeam/ProjectUnityPublic#47]
![editing bugs](https://user-images.githubusercontent.com/78838382/163379123-b08dc89d-60a5-45c6-894b-68dab34d0b17.png)

This in editor
Welp the stick link extend outta nowhere

**Comment by Hot-Sausage07** [comment]
want more
![want more bugs](https://user-images.githubusercontent.com/78838382/163382014-96147d26-259d-484c-b279-15fe4bfb5df8.png)
sticks
grey sticks

**Comment by Xeloboyo** [comment]
should be fixed next update
