### ISSUE TITLE
PU's error while loading game

### ISSUE THREAD

**Issue by Thesussy** [AvantTeam/ProjectUnityPublic#50]
I just wanted play the newest Pu on Erekir relase, but the game crashed while loading mod. And i can't play Erekir with PU

**Comment by MEEPofFaith** [comment]
Did you really just try to play PU with Erekir only 18 minutes after the branch was created and the process of porting ***began***?

*It's been almost an entire week since I started porting PM to Erekir and it's still not done.*

**Comment by Anuken** [comment]
~~The issue isn't really how soon it was, it's that we have absolutely no idea what commit was used, what BE build was used, what the error was or where it even happened.~~

**Comment by MEEPofFaith** [comment]
~~Fair~~
