### ISSUE TITLE
Youngcha Drills/Factories Producing Resources Without Torque/Rpm

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [AvantTeam/ProjectUnityPublic#53]
https://user-images.githubusercontent.com/82627347/170764949-d5fb852e-b42d-4e37-a635-121271128524.mp4

Platform: Android

Build: 22568 Be Erekir version

Mod Version: Java CI #94 Commit:[06d3ae2](https://github.com/AvantTeam/ProjectUnityPublic/commit/06d3ae28cd4b8b68d1f8b1690e7943b49ec13243) Erekir-Port

Issue:Well I was testing with Project Unity to Erekir to how they're interacted so first I place a youngcha wall drill into a vanilla graphite wall. As I about to place a torque source the wall drill mined a graphite with 0.0rpm producing it without  any torque sources connected to a wall drill.

**Comment by Xeloboyo** [comment]
hmm will look into it, thanks
