### ISSUE TITLE
Game crashing after killing a modular unit

### ISSUE THREAD

**Issue by PlanetSat0rn** [AvantTeam/ProjectUnityPublic#57]
Whenever a modular unit dies, the save becomes unusable.
![image](https://user-images.githubusercontent.com/109532054/182851711-97d4415b-d3a3-479c-b0cd-a4fe65f5033f.png)

**Comment by PlanetSat0rn** [comment]
[crash-report-08_04_2022_08_56_18.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/9260053/crash-report-08_04_2022_08_56_18.txt)

**Comment by PlanetSat0rn** [comment]
also this only happens in erekir-port

**Comment by xStaBUx** [comment]
> also this only happens in erekir-port

hmm i didn`t say it

**Comment by Xeloboyo** [comment]
Bug just randomly appears fsr, try using a different build.
