### ISSUE TITLE
Youngcha parts avalible in erekir is wildly inconsistent

### ISSUE THREAD

**Issue by Xeloboyo** [AvantTeam/ProjectUnityPublic#68]
![image](https://user-images.githubusercontent.com/13158938/186001550-a935bdc3-eb47-4683-ac98-b469d42305b3.png)
Expected behaviour:
All parts with some exceptions are available
Actual behaviour:
The belt connectors, arms, and some crucible buildings are available

**Comment by BlueWolf3682** [comment]
this is due to the game filtering out any serpulo material that isnt on erekir - this is more a issue that should be adressed as a game bug, as this filter messes up other mods as well

**Comment by Xeloboyo** [comment]
very well, not fixing then.
