### ISSUE TITLE
assembly arms run regardless of rpm input

### ISSUE THREAD

**Issue by BlueWolf3682** [AvantTeam/ProjectUnityPublic#69]
![image](https://user-images.githubusercontent.com/61173114/186004486-278aafdf-e760-4315-b0dd-b799be3c8793.png)

**Comment by Xeloboyo** [comment]
nice lasers, is this just visual or is it actually just building at full speed?

**Comment by BlueWolf3682** [comment]
it is building at full speed

**Comment by Xeloboyo** [comment]
Fixed

**Comment by EclipseTheOldOne** [comment]
issue 69
nice
