### ISSUE TITLE
Crash on Startup (Shaders)

### ISSUE THREAD

**Issue by AdvintasAHAT86420** [AvantTeam/ProjectUnityPublic#72]
Platform: Android (Galaxy Tab A7 Lite)

Build: Alpha 138.1

Mod Version: Java CI #111: Commit 9af43c2 pushed by Xeloboyo

Issue: 
Mindustry has crashed. How unfortunate.
Version: alpha build 138.1
OS: Linux xnull (aarch64)
Android API level: 30
Java Version: 0
Runtime Available Memory: 256mb
Cores: 8
Mods: unity:0.1-youngcha.2.8

> IllegalArgument: 'Failed to compile shader: Vertex shader
Success.
Fragment shader:
Compile failed.
ERROR: 0:77: 'f' : suffix for floats requires language version 300
1 compilation errors. No code generated.

'
Shader.<init>: 25
Shader.<init>: 37
UnityShaders$GroundLiquidShader.<init>: 73
UnityShaders.load: 46
-$$Lambda$cqeWWcz-HLQYkgIIZ0u-NAF_rRA.run: 0
AndroidGraphics.onDrawFrame: 15
GLSurfaceView$GLThread.guardedRun: 1591
GLSurfaceView$GLThread.run: 1286

**Comment by GlennFolker** [comment]
@Xeloboyo you should always do `1.0` instead of `1f` to avoid this exact problem..

**Comment by Xeloboyo** [comment]
Yeah i keep forgetting mobile exists
