### ISSUE TITLE
modular units don't work

### ISSUE THREAD

**Issue by littlekatter330** [AvantTeam/ProjectUnityPublic#78]
THEY CRASH THE GAME WHEN THEY SPAWN.                                      please fix now

**Comment by ThePythonGuy3** [comment]
Hm yes very descriptive indeed

**Comment by PlanetSat0rn** [comment]
how to not put a issue request

**Comment by Comrad501** [comment]
i double that
 
![image](https://user-images.githubusercontent.com/117436035/199924853-5c25e09e-8be7-4de2-a0c9-11b8e0cf6a19.png)

**Comment by Xeloboyo** [comment]
mod currently updated to latest mindustry version so probably fixed.
