### ISSUE TITLE
Game crashes when I download mod

### ISSUE THREAD

**Issue by crutoi** [AvantTeam/ProjectUnityPublic#79]
Its says "NoClassDefFoundError:arc/graphics(wrong name:arc/Graphics)"
[crash-report-11_05_2022_14_13_54.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/10014794/crash-report-11_05_2022_14_13_54.txt)

**Comment by crutoi** [comment]
[crash-report-11_05_2022_14_13_54.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/10014534/crash-report-11_05_2022_14_13_54.txt)

**Comment by Xeloboyo** [comment]
Mod used in wrong game version

**Comment by crutoi** [comment]
It still crashes no matter which version I use
