### ISSUE TITLE
tank crash

### ISSUE THREAD

**Issue by MrRoomba69** [AvantTeam/ProjectUnityPublic#83]
![Crash report](https://user-images.githubusercontent.com/118114584/202325508-2192d323-74bf-4db8-b32c-eb6928d07de3.png)

When I try to control a custom tank on steam 140.4 with foo's client the game crashes. Attached crash report

**Comment by Austin5003** [comment]
🍞

**Comment by MrRoomba69** [comment]
> 🍞

🍞

**Comment by MEEPofFaith** [comment]
1. We can't fix anything without a crash report saying exactly where the problem occurs.
2. It may be caused by foo's client. Contact @buthed010203 instead.

**Comment by MrRoomba69** [comment]
> 1. We can't fix anything without a crash report saying exactly where the problem occurs.
> 2. Since I don't use foo's client and don't crash, the problem is likely due to foo's client. Contact @buthed010203 instead.

Just attached crash report

**Comment by buthed010203** [comment]
> * We can't fix anything without a crash report saying exactly where the problem occurs.
> * Since I don't use foo's client and don't crash, the problem is likely due to foo's client. Contact @buthed010203 instead.

How could your method being abstract be caused by me 💀

**Comment by buthed010203** [comment]
Ah wait foo added some abstract method to the interface that your generated units don't add a method for i see

**Comment by buthed010203** [comment]
Should be fixed now

**Comment by MrRoomba69** [comment]
> Should be fixed now

will check

**Comment by buthed010203** [comment]
Classic, jitpack is dead

**Comment by buthed010203** [comment]
> > Should be fixed now
> 
> did not work ![crash report 2](https://user-images.githubusercontent.com/118114584/202328282-c3950a4d-dba9-40bd-82ae-24a2d6240ed4.png)

what build is this

**Comment by MrRoomba69** [comment]
> > > Should be fixed now
> > 
> > 
> > did not work ![crash report 2](https://user-images.githubusercontent.com/118114584/202328282-c3950a4d-dba9-40bd-82ae-24a2d6240ed4.png)
> 
> what build is this

now it works

**Comment by MrRoomba69** [comment]
The bug has been fixed. Closed issue
