### ISSUE TITLE
Game still crashes with same issue no matter which version I use

### ISSUE THREAD

**Issue by crutoi** [AvantTeam/ProjectUnityPublic#85]
[crash-report-11_17_2022_08_21_50.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/10028579/crash-report-11_17_2022_08_21_50.txt)
[crash-report-11_17_2022_08_16_04.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/10028580/crash-report-11_17_2022_08_16_04.txt)

**Comment by crutoi** [comment]
Does it work only on v6?

**Comment by crutoi** [comment]
Or v7 too?

**Comment by Xeloboyo** [comment]
Youngcha 2.8 ran on v137

**Comment by crutoi** [comment]
What do you mean?

**Comment by crutoi** [comment]
[crash-report-11_17_2022_14_39_09.txt](https://github.com/AvantTeam/ProjectUnityPublic/files/10031531/crash-report-11_17_2022_14_39_09.txt)
