### ISSUE TITLE
crash with crucible source

### ISSUE THREAD

**Issue by MrRoomba69** [AvantTeam/ProjectUnityPublic#99]
![image](https://github.com/AvantTeam/ProjectUnityPublic/assets/118114584/5f95879d-90de-4be9-a83b-1ebc863a34ae)
when i place a crucible source i get this error

**Comment by Radio-Silence-1** [comment]
thats normal, and wont be fixed, mod is dead. Just dont place them

**Comment by MrRoomba69** [comment]
it was fixed an a mystery update
